stages:
  - build

generate-image-gcc:
  stage: build
  tags: 
    - linux/x86_64 
  
  before_script:
    - apt update 
    - apt install build-essential -y
    - apt install libmpfr-dev -y
    - apt install libgmp3-dev -y
    - apt install libmpc-dev -y
    - apt install zlib1g-dev -y
    - apt install wget -y
    - apt install gcc-multilib -y

    - docker login kds4wexp.gitlab.yandexcloud.net:5050

  script:
    - mkdir build
    - cd build
    - wget http://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.gz
    - tar -xf gcc-13.2.0.tar.gz
    - rm gcc-13.2.0.tar.gz
    - cd gcc-13.2.0
    - ./contrib/download_prerequisites
    - ./configure --enable-bootstrap --enable-languages=c,c++ --prefix=/usr --program-suffix=-13.2 --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-libstdcxx-backtrace --with-libstdcxx-zoneinfo=/usr/share/zoneinfo --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --enable-offload-defaulted --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_64=icelake-server --build=x86_64-redhat-linux --with-build-config=bootstrap-lto --enable-link-serialization=1 --with-default-libstdcxx-abi=new --with-build-config=bootstrap-lto
    - make -j4
    - make install -j4

  after_script:
    - docker build -t kds4wexp.gitlab.yandexcloud.net:5050/dmitry_belov/test_project .
    - docker push kds4wexp.gitlab.yandexcloud.net:5050/dmitry_belov/test_project

  # - push docker registry  
  artifacts:
    paths:
      - build/
