name: Build
on:
  push:
    branches:
      - main
      - auto/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v4
      - name: Run build.py
        run: |
          build.py