name: Deploy
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Run deploy.py
        run: |
          python ./ci/scripts/deploy.py