name: Pipeline
on:
  push:
    branches:
      - main
      - auto/*

permissions:
  contents: read # for checkout

jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    # runs-on: self-hosted
    # container: 
    #   image: gcc:12.4.0
    steps:

      - name: Pipeline
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: |
          npm install --save-dev semantic-release \
                      @semantic-release/exec \
                      @semantic-release/changelog 

      - name: Run build.py
        run: |
          python ./ci/scripts/build.py

      - name: Run test.py
        run: |
          python ./ci/scripts/test.py

      - name: Generate last_tag.env & CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
        run: |
          npx semantic-release

        
      - name: DEBUG
        run: echo $last_tag.env

      - name: Run deploy.py
        run: |
          python ./ci/scripts/deploy.py