name: Test
on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Test
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Run test.py
        run: |
          python ./ci/scripts/test.py